// Stable error codes returned over the local protocol (dev principles §5).
// Strings are the wire contract; never renumber or reuse. Add new codes at end.
export const ErrorCode = {
  PROTOCOL_HANDSHAKE_FAILED: 'protocol.handshake_failed',
  PROTOCOL_VERSION_MISMATCH: 'protocol.version_mismatch',
  PROTOCOL_AUTH_REJECTED: 'protocol.auth_rejected',
  PROTOCOL_FRAME_MALFORMED: 'protocol.frame_malformed',
  PROTOCOL_UNEXPECTED_REQUEST: 'protocol.unexpected_request',
  RUN_NOT_FOUND: 'run.not_found',
  RUN_INVALID_STATE: 'run.invalid_state',
  STEP_NOT_FOUND: 'step.not_found',
  WORKSPACE_NOT_FOUND: 'workspace.not_found',
  TASK_NOT_FOUND: 'task.not_found',
  TASK_VERSION_MISMATCH: 'task.version_mismatch',
  MODEL_NOT_CONFIGURED: 'model.not_configured',
  MODEL_OVERRIDE_OUTSIDE_RUN: 'model.override_outside_run',
  CREDENTIAL_PIN_VIOLATION: 'credential.pin_violation',
  CREDENTIAL_GROUP_EMPTY: 'credential.group_empty',
  PROVIDER_CALL_FAILED: 'provider.call_failed',
  PROVIDER_AUTH_FAILED: 'provider.auth_failed',
  PROVIDER_TIMEOUT: 'provider.timeout',
  PROVIDER_RATE_LIMITED: 'provider.rate_limited',
  PROVIDER_PROTOCOL_INCOMPATIBLE: 'provider.protocol_incompatible',
  APPROVAL_REQUIRED: 'approval.required',
  APPROVAL_DENIED: 'approval.denied',
  HUMAN_ONLY_ACTION: 'approval.human_only',
  MIGRATION_FAILED: 'storage.migration_failed',
  DB_BACKUP_FAILED: 'storage.db_backup_failed',
  STORAGE_WRITE_FAILED: 'storage.write_failed',
  PATH_TRAVERSAL: 'security.path_traversal',
  UNAUTHORIZED_TOOL: 'security.unauthorized_tool',
  SECRET_SCRUB_FAILED: 'security.secret_scrub_failed',
  WORKER_CRASHED: 'worker.crashed',
  WORKER_TIMEOUT: 'worker.timeout',
  BROWSER_HANDOFF_NOT_FOUND: 'browser.handoff-not-found',
  BROWSER_HANDOFF_NOT_WAITING: 'browser.handoff-not-waiting',
  BROWSER_HANDOFF_ALREADY_CANCELLED: 'browser.handoff-already-cancelled',
  BROWSER_HANDOFF_REVISION_CONFLICT: 'browser.handoff-revision-conflict',
  BROWSER_HANDOFF_CONFLICT: 'browser.handoff-conflict',
  BROWSER_HANDOFF_CHECKPOINT_INVALID: 'browser.handoff-checkpoint-invalid',
  BROWSER_HANDOFF_OWNERSHIP_MISMATCH: 'browser.handoff-ownership-mismatch',
  BROWSER_HANDOFF_HOST_UNAVAILABLE: 'browser.handoff-host-unavailable',
  BROWSER_HANDOFF_BINDING_INVALID: 'browser.handoff-binding-invalid',
  BROWSER_HANDOFF_UNAVAILABLE: 'browser.handoff-unavailable',
  DESKTOP_HOST_HANDSHAKE_FAILED: 'desktop.host-handshake-failed',
  DESKTOP_TIMEOUT: 'desktop.timeout',
  DESKTOP_CANCELLED: 'desktop.cancelled',
  DESKTOP_CRASHED: 'desktop.crashed',
  DESKTOP_PERMISSION_DENIED: 'desktop.permission-denied',
  DESKTOP_UIA_UNAVAILABLE: 'desktop.uia-unavailable',
  DESKTOP_ACTION_UNSUPPORTED: 'desktop.action-unsupported',
  DESKTOP_PLATFORM_UNSUPPORTED: 'desktop.platform-unsupported',
  DESKTOP_PROTOCOL_MALFORMED: 'desktop.protocol-malformed',
  DESKTOP_WINDOW_STALE: 'desktop.window-stale',
  DESKTOP_SNAPSHOT_STALE: 'desktop.snapshot-stale',
  DESKTOP_SELECTOR_NOT_FOUND: 'desktop.selector-not-found',
  DESKTOP_SELECTOR_AMBIGUOUS: 'desktop.selector-ambiguous',
  DESKTOP_ELEMENT_NOT_FOUND: 'desktop.element-not-found',
  DESKTOP_ELEMENT_DISABLED: 'desktop.element-disabled',
  DESKTOP_ELEMENT_OFFSCREEN: 'desktop.element-offscreen',
  DESKTOP_PATTERN_UNSUPPORTED: 'desktop.pattern-unsupported',
  DESKTOP_VALUE_READ_ONLY: 'desktop.value-read-only',
  DESKTOP_ACTION_FAILED: 'desktop.action-failed',
  DESKTOP_CAPABILITY_DISABLED: 'desktop.capability-disabled',
  DESKTOP_INPUT_MONITOR_UNAVAILABLE: 'desktop.input-monitor-unavailable',
  DESKTOP_USER_INPUT_DETECTED: 'desktop.user-input-detected',
  DESKTOP_COMMAND_INSPECTION_REQUIRED: 'desktop.command-inspection-required',
  DESKTOP_COMMAND_CONFLICT: 'desktop.command-conflict',
  DESKTOP_COMMAND_CANCELLED: 'desktop.command-cancelled',
  DESKTOP_APP_LAUNCH_FAILED: 'desktop.app-launch-failed',
  DESKTOP_APP_WINDOW_NOT_FOUND: 'desktop.app-window-not-found',
  BROWSER_PROFILE_NOT_FOUND: 'browser.profile-not-found',
  BROWSER_PROFILE_IN_USE: 'browser.profile-in-use',
  BROWSER_PROFILE_HAS_WORKFLOWS: 'browser.profile-has-workflows',
  BROWSER_PROFILE_REVISION_CONFLICT: 'browser.profile-revision-conflict',
  BROWSER_DEFAULT_PROFILE_IMMUTABLE: 'browser.default-profile-immutable',
  BROWSER_SITE_SESSION_NOT_FOUND: 'browser.site-session-not-found',
  BROWSER_PROFILE_HOST_UNAVAILABLE: 'browser.profile-host-unavailable',
  BROWSER_PROFILE_OPERATION_FAILED: 'browser.profile-operation-failed',
  BROWSER_RECORDING_NOT_FOUND: 'browser.recording-not-found',
  BROWSER_RECORDING_CONFLICT: 'browser.recording-conflict',
  BROWSER_RECORDING_HOST_UNAVAILABLE: 'browser.recording-host-unavailable',
  BROWSER_RECORDING_OPERATION_FAILED: 'browser.recording-operation-failed',
  BROWSER_WORKFLOW_NOT_FOUND: 'browser.workflow-not-found',
  BROWSER_WORKFLOW_CONFLICT: 'browser.workflow-conflict',
  BROWSER_WORKFLOW_OPERATION_FAILED: 'browser.workflow-operation-failed',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface AppError {
  code: ErrorCode;
  /** User-actionable message (never carries secrets). */
  message: string;
  detail?: unknown;
  /** Diagnostic reference id; raw evidence lives in secret-scrubbed diagnostic store. */
  diagnosticRefId?: string;
}
