import { lazy, Suspense } from 'react';
const AgentWorkspaceFixture = lazy(() => import('./AgentWorkspaceFixture.js'));
const TaskListFixture = lazy(() => import('./TaskListFixture.js'));
const ConversationalHandoffLiveFixture = lazy(() => import('./ConversationalHandoffLiveFixture.js'));
const ConversationalHandoffFixture = lazy(() => import('./ConversationalHandoffFixture.js'));
const StagedDispatchFixture = lazy(() => import('./StagedDispatchFixture.js'));
const WorkbenchVisualFixture = lazy(() => import('./WorkbenchVisualFixture.js'));
import { createRoot } from 'react-dom/client';
import { Phase3VisualFixture, resolvePhase3VisualCase } from './Phase3VisualFixture.js';

const params = new URLSearchParams(window.location.search);
const visualCase = resolvePhase3VisualCase(window.location.search);
const agentWorkspaceCase = params.get('phase3-visual') === 'agent-workspace';
const taskListCase = params.get('phase3-visual') === 'task-list-reference';
const liveHandoffCase = params.get('phase3-visual') === 'conversational-handoff-live';
const conversationalHandoffCase = params.get('phase3-visual') === 'conversational-handoff';
const stagedDispatchCase = params.get('phase3-visual') === 'staged-dispatch';
const workbenchCase = params.get('phase3-visual') === 'workbench';
if (!visualCase && !agentWorkspaceCase && !workbenchCase && !taskListCase && !stagedDispatchCase && !conversationalHandoffCase && !liveHandoffCase) throw new Error('Missing or invalid Phase 3 visual case');
const theme = params.get('theme') === 'dark' ? 'dark' : 'light';
document.documentElement.classList.toggle('dark', theme === 'dark');
document.documentElement.dataset.phase3Theme = theme;
if (agentWorkspaceCase && params.get('shell-context') === 'embedded') document.documentElement.dataset.shellDesign = 'agent';
document.documentElement.toggleAttribute('data-reduced-motion', params.get('motion') !== 'full');
const container = document.getElementById('root');
if (!container) throw new Error('missing #root');
createRoot(container).render(liveHandoffCase ? <Suspense fallback={<p>正在载入本地实际执行验收…</p>}><ConversationalHandoffLiveFixture /></Suspense> : conversationalHandoffCase ? <Suspense fallback={<p>正在载入 @协作验收…</p>}><ConversationalHandoffFixture /></Suspense> : stagedDispatchCase ? <Suspense fallback={<p>正在载入逐阶段派工验收…</p>}><StagedDispatchFixture /></Suspense> : taskListCase ? <Suspense fallback={<p>正在载入任务日志…</p>}><TaskListFixture /></Suspense> : workbenchCase ? <Suspense fallback={<p>正在载入完整工作区…</p>}><WorkbenchVisualFixture /></Suspense> : agentWorkspaceCase ? <Suspense fallback={<p>正在载入智能体 UI 验收…</p>}><AgentWorkspaceFixture /></Suspense> : <Phase3VisualFixture visualCase={visualCase!} />);
