/**
 * Ad / tracker host suffixes blocked before the request leaves the guest.
 *
 * NewMax ships its own list inside the minified main bundle and never exposes
 * it; this is an equivalent curated list of well-known ad and analytics
 * suffixes. Matching is suffix-based, so `ads.example.com` matches `example.com`
 * only when the entry is the registrable domain, and `doubleclick.net` also
 * covers `static.doubleclick.net`.
 */
export const BLOCKED_AD_HOST_SUFFIXES: readonly string[] = [
  '2mdn.net',
  'ad.doubleclick.net',
  'adnxs.com',
  'adsafeprotected.com',
  'adservice.google.com',
  'adsrvr.org',
  'advertising.com',
  'amazon-adsystem.com',
  'amplitude.com',
  'appsflyer.com',
  'bat.bing.com',
  'bidswitch.net',
  'branch.io',
  'casalemedia.com',
  'criteo.com',
  'criteo.net',
  'demdex.net',
  'doubleclick.net',
  'everesttech.net',
  'facebook.net',
  'google-analytics.com',
  'googleadservices.com',
  'googlesyndication.com',
  'googletagmanager.com',
  'googletagservices.com',
  'hotjar.com',
  'imrworldwide.com',
  'indexww.com',
  'inmobi.com',
  'intercom.io',
  'krxd.net',
  'mathtag.com',
  'mixpanel.com',
  'moatads.com',
  'mopub.com',
  'newrelic.com',
  'openx.net',
  'outbrain.com',
  'pubmatic.com',
  'quantserve.com',
  'rubiconproject.com',
  'scorecardresearch.com',
  'segment.io',
  'serving-sys.com',
  'sharethrough.com',
  'smaato.net',
  'smartadserver.com',
  'spotxchange.com',
  'taboola.com',
  'teads.tv',
  'tremorhub.com',
  'turn.com',
  'yieldmo.com',
  'zedo.com',
];
