export {
  tryParseGetBrowserRecordingPayload as parseGetBrowserRecordingPayload,
  tryParseListBrowserRecordingsPayload as parseListBrowserRecordingsPayload,
  tryParseStartBrowserRecordingPayload as parseStartBrowserRecordingPayload,
  tryParseStopBrowserRecordingPayload as parseStopBrowserRecordingPayload,
  tryParsePauseBrowserRecordingPayload as parsePauseBrowserRecordingPayload,
  tryParseResumeBrowserRecordingPayload as parseResumeBrowserRecordingPayload,
} from '@sync-think/protocol/browser-payloads';
